name: SuperGod
main: me.ceramictitan.SuperGod.SuperGod
version: ${project.version}
description: >
             Invinciblity plugin.
commands:
  jesus:
    description: make player invincible.
    permissions: simply.jesus
    aliases: [j]
    usage: /<command>
  unjesus:
    description: makes player vulnerable.
    permissions: simply.unjesus
    aliases: [uj]
    usage: /<command>